[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cv"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
render = { path = "../render" }
oxidize-pdf = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
